/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/': RouteRecordInfo<
      '/composables/',
      '/composables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/basic': RouteRecordInfo<
      '/composables/basic',
      '/composables/basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/counter': RouteRecordInfo<
      '/composables/counter',
      '/composables/counter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/nested': RouteRecordInfo<
      '/composables/nested',
      '/composables/nested',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/page-refactor/': RouteRecordInfo<
      '/composables/page-refactor/',
      '/composables/page-refactor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/page-refactor/page-after': RouteRecordInfo<
      '/composables/page-refactor/page-after',
      '/composables/page-refactor/page-after',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/page-refactor/page-after-explained': RouteRecordInfo<
      '/composables/page-refactor/page-after-explained',
      '/composables/page-refactor/page-after-explained',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/page-refactor/page-before': RouteRecordInfo<
      '/composables/page-refactor/page-before',
      '/composables/page-refactor/page-before',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/page-refactor/page-before-explained': RouteRecordInfo<
      '/composables/page-refactor/page-before-explained',
      '/composables/page-refactor/page-before-explained',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/users/': RouteRecordInfo<
      '/composables/users/',
      '/composables/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/users/list-one-big-component': RouteRecordInfo<
      '/composables/users/list-one-big-component',
      '/composables/users/list-one-big-component',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/composables/users/list-using-composables': RouteRecordInfo<
      '/composables/users/list-using-composables',
      '/composables/users/list-using-composables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/props': RouteRecordInfo<
      '/props',
      '/props',
      Record<never, never>,
      Record<never, never>,
      | '/props/multiple-types'
    >,
    '/props/multiple-types': RouteRecordInfo<
      '/props/multiple-types',
      '/props/multiple-types',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/provide-and-inject/': RouteRecordInfo<
      '/provide-and-inject/',
      '/provide-and-inject',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/provide-and-inject/dashboard-user-context': RouteRecordInfo<
      '/provide-and-inject/dashboard-user-context',
      '/provide-and-inject/dashboard-user-context',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/provide-and-inject/string-key': RouteRecordInfo<
      '/provide-and-inject/string-key',
      '/provide-and-inject/string-key',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/refs-reactive/': RouteRecordInfo<
      '/refs-reactive/',
      '/refs-reactive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/refs-reactive/reactive': RouteRecordInfo<
      '/refs-reactive/reactive',
      '/refs-reactive/reactive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/refs-reactive/ref': RouteRecordInfo<
      '/refs-reactive/ref',
      '/refs-reactive/ref',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stores/': RouteRecordInfo<
      '/stores/',
      '/stores',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stores/app-store': RouteRecordInfo<
      '/stores/app-store',
      '/stores/app-store',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stores/feature-store': RouteRecordInfo<
      '/stores/feature-store',
      '/stores/feature-store',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/styles/': RouteRecordInfo<
      '/styles/',
      '/styles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/styles/css-module': RouteRecordInfo<
      '/styles/css-module',
      '/styles/css-module',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/typescript/': RouteRecordInfo<
      '/typescript/',
      '/typescript',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/typescript/never-use-any': RouteRecordInfo<
      '/typescript/never-use-any',
      '/typescript/never-use-any',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/typescript/type-vs-interface': RouteRecordInfo<
      '/typescript/type-vs-interface',
      '/typescript/type-vs-interface',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/v-if/': RouteRecordInfo<
      '/v-if/',
      '/v-if',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/v-if/large-v-if': RouteRecordInfo<
      '/v-if/large-v-if',
      '/v-if/large-v-if',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/v-if/split-components': RouteRecordInfo<
      '/v-if/split-components',
      '/v-if/split-components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/composables/index.vue': {
      routes:
        | '/composables/'
      views:
        | never
    }
    'src/pages/composables/basic.vue': {
      routes:
        | '/composables/basic'
      views:
        | never
    }
    'src/pages/composables/counter.vue': {
      routes:
        | '/composables/counter'
      views:
        | never
    }
    'src/pages/composables/nested.vue': {
      routes:
        | '/composables/nested'
      views:
        | never
    }
    'src/pages/composables/page-refactor/index.vue': {
      routes:
        | '/composables/page-refactor/'
      views:
        | never
    }
    'src/pages/composables/page-refactor/page-after.vue': {
      routes:
        | '/composables/page-refactor/page-after'
      views:
        | never
    }
    'src/pages/composables/page-refactor/page-after-explained.vue': {
      routes:
        | '/composables/page-refactor/page-after-explained'
      views:
        | never
    }
    'src/pages/composables/page-refactor/page-before.vue': {
      routes:
        | '/composables/page-refactor/page-before'
      views:
        | never
    }
    'src/pages/composables/page-refactor/page-before-explained.vue': {
      routes:
        | '/composables/page-refactor/page-before-explained'
      views:
        | never
    }
    'src/pages/composables/users/index.vue': {
      routes:
        | '/composables/users/'
      views:
        | never
    }
    'src/pages/composables/users/list-one-big-component.vue': {
      routes:
        | '/composables/users/list-one-big-component'
      views:
        | never
    }
    'src/pages/composables/users/list-using-composables.vue': {
      routes:
        | '/composables/users/list-using-composables'
      views:
        | never
    }
    'src/pages/props.vue': {
      routes:
        | '/props'
        | '/props/multiple-types'
      views:
        | 'default'
    }
    'src/pages/props/multiple-types.vue': {
      routes:
        | '/props/multiple-types'
      views:
        | never
    }
    'src/pages/provide-and-inject/index.vue': {
      routes:
        | '/provide-and-inject/'
      views:
        | never
    }
    'src/pages/provide-and-inject/dashboard-user-context.vue': {
      routes:
        | '/provide-and-inject/dashboard-user-context'
      views:
        | never
    }
    'src/pages/provide-and-inject/string-key.vue': {
      routes:
        | '/provide-and-inject/string-key'
      views:
        | never
    }
    'src/pages/refs-reactive/index.vue': {
      routes:
        | '/refs-reactive/'
      views:
        | never
    }
    'src/pages/refs-reactive/reactive.vue': {
      routes:
        | '/refs-reactive/reactive'
      views:
        | never
    }
    'src/pages/refs-reactive/ref.vue': {
      routes:
        | '/refs-reactive/ref'
      views:
        | never
    }
    'src/pages/stores/index.vue': {
      routes:
        | '/stores/'
      views:
        | never
    }
    'src/pages/stores/app-store.vue': {
      routes:
        | '/stores/app-store'
      views:
        | never
    }
    'src/pages/stores/feature-store.vue': {
      routes:
        | '/stores/feature-store'
      views:
        | never
    }
    'src/pages/styles/index.vue': {
      routes:
        | '/styles/'
      views:
        | never
    }
    'src/pages/styles/css-module.vue': {
      routes:
        | '/styles/css-module'
      views:
        | never
    }
    'src/pages/typescript/index.vue': {
      routes:
        | '/typescript/'
      views:
        | never
    }
    'src/pages/typescript/never-use-any.vue': {
      routes:
        | '/typescript/never-use-any'
      views:
        | never
    }
    'src/pages/typescript/type-vs-interface.vue': {
      routes:
        | '/typescript/type-vs-interface'
      views:
        | never
    }
    'src/pages/v-if/index.vue': {
      routes:
        | '/v-if/'
      views:
        | never
    }
    'src/pages/v-if/large-v-if.vue': {
      routes:
        | '/v-if/large-v-if'
      views:
        | never
    }
    'src/pages/v-if/split-components.vue': {
      routes:
        | '/v-if/split-components'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
